# Generated by Django 5.2.1 on 2025-05-28 15:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dashboard', '0001_initial'), ('dashboard', '0002_alter_normal_rareweapons_alter_normal_weapons'), ('dashboard', '0003_alter_normal_rareweapons_alter_normal_weapons'), ('dashboard', '0004_alter_rewardgear_id_alter_rewardgear_rewardid'), ('dashboard', '0005_auto_20250528_1521')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RewardGear',
            fields=[
                ('rewardId', models.CharField(primary_key=True, serialize=False)),
                ('kind', models.CharField()),
                ('id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RewardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField()),
                ('topPercent', models.IntegerField()),
                ('minimumScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BigRun',
            fields=[
                ('phaseId', models.CharField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('stage', models.IntegerField()),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('rareWeapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bigBoss', models.CharField()),
                ('rewards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.phaserewards')),
            ],
        ),
        migrations.AddField(
            model_name='phaserewards',
            name='bronze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze_reward', to='dashboard.rewardinfo'),
        ),
        migrations.AddField(
            model_name='phaserewards',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_reward', to='dashboard.rewardinfo'),
        ),
        migrations.AddField(
            model_name='phaserewards',
            name='normal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_reward', to='dashboard.rewardinfo'),
        ),
        migrations.AddField(
            model_name='phaserewards',
            name='silver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_reward', to='dashboard.rewardinfo'),
        ),
        migrations.CreateModel(
            name='TeamContest',
            fields=[
                ('phaseId', models.CharField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('stage', models.IntegerField()),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('rareWeapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('specials', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('rewards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.phaserewards')),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('bigBoss', models.CharField()),
                ('phaseId', models.CharField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('stage', models.IntegerField()),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=4)),
                ('rareWeapons', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('rewardGear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rewardgear')),
            ],
        ),
    ]
