# Generated by Django 5.2.1 on 2025-05-22 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal',
            name='rareWeapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='normal',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=4),
        ),
    ]
