# Generated by Django 5.2.1 on 2025-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_normal_rareweapons_alter_normal_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardgear',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rewardgear',
            name='rewardId',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
