# Generated by Django 5.2.1 on 2025-05-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_rewardgear_id_alter_rewardgear_rewardid'),
    ]

    operations = [
    ]
