# Generated by Django 5.2.1 on 2025-06-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0005_auto_20250528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal',
            name='bigBoss',
            field=models.CharField(null=True),
        ),
    ]
