# Generated by Django 5.2.1 on 2025-06-06 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_normal_bigboss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigrun',
            name='bigBoss',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='bigrun',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
    ]
