# Generated by Django 5.2.1 on 2025-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_bigrun_bigboss_alter_bigrun_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='rewardinfo',
            name='reward',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
