# Generated by Django 5.2.1 on 2025-06-10 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_rewardinfo_id_alter_rewardinfo_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=4),
        ),
    ]
