# Generated by Django 5.2.1 on 2025-06-10 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_normal_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_default=-1, default=-1), default=list, size=4),
        ),
    ]
