# Generated by Django 5.2.1 on 2025-06-10 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_bigrun_weapons_alter_teamcontest_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigrun',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=4),
        ),
        migrations.AlterField(
            model_name='normal',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=4),
        ),
        migrations.AlterField(
            model_name='teamcontest',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=4),
        ),
    ]
